[functions]
  directory = "proxy/src"
  node_bundler = "esbuild"
  included_files = ["proxy/dist/**"]
[[redirects]]
   from = "/*"
   status = 200
   to = "/.netlify/functions/index/:splat"
   force = true
